# Generated by Django 4.1.4 on 2022-12-29 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_date='published_date')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('tools_used', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='data_analysis')),
            ],
            options={
                'ordering': ('-published_date',),
            },
        ),
    ]
