# Generated by Django 4.1.7 on 2023-03-09 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(max_length=200, unique_for_date="published_date"),
                ),
                ("published_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "thumbnail",
                    models.FileField(blank=True, null=True, upload_to="articles"),
                ),
                (
                    "category",
                    models.CharField(default="Article", editable=False, max_length=20),
                ),
            ],
            options={
                "ordering": ("-published_date",),
            },
        ),
    ]
